### ISSUE TITLE
serialport这个模块在win上貌似不工作，打开你的bat后无法访问

### ISSUE THREAD

**Issue by buzai** [xianyanbu/serialport#1]
您是在win下安装的吗，我有安装vs2012，python2.7，但是那个模块就是不工作。

**Comment by xianyanbu** [comment]
```
是的，所有的开发都是在win下进行的。
```

xianyan.bu@qq.com

发件人： chenLX
发送时间： 2016-05-20 11:48
收件人： xianyanbu/serialport
主题： [xianyanbu/serialport] serialport这个模块在win上貌似不工作，打开你的bat后无法访问 (#1)
您是在win下安装的吗，我有安装vs2012，python2.7，但是那个模块就是不工作。

**Comment by buzai** [comment]
comDemo/node_modules/bindings/bindings.js:91
  throw err
请问类似这样的错误需要怎么解决，花了很久的时间来寻找解决方法可是就是不行

**Comment by xianyanbu** [comment]
```
遇到这样的问题，throw err是不能得到出错信息的，你打印出出错信息看看，console.log(err)，这样能帮助我们进一步确认错误的原因，因为它的错误信息提示会更明确些，如果还是无法判断错误原因或者无法解决，这个时候再根据得到相应的错误标识或者错误编码去网上检索，也会更快些。    
```

xianyan.bu@qq.com

发件人： chenLX
发送时间： 2016-05-20 17:01
收件人： xianyanbu/serialport
抄送： xianyanbu; Comment
主题： Re: [xianyanbu/serialport] serialport这个模块在win上貌似不工作，打开你的bat后无法访问 (#1)
comDemo/node_modules/bindings/bindings.js:91
throw err
请问类似这样的错误需要怎么解决，花了很久的时间来寻找解决方法可是就是不行

**Comment by buzai** [comment]
很感谢你的帮助，我现在换到了ubuntu上面再次尝试使用这个模块，我用minicom检测到了数据，确认我的串口是可以的读到数据的。

我在 app.js 里面只写了一句话---   var SerialPort = require("serialport")

然后运行就报错，错误信息如下：
/home/chenhao/Desktop/comDemo/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /home/chenhao/Desktop/comDemo/node_modules/serialport/build/serialport.node
 → /home/chenhao/Desktop/comDemo/node_modules/serialport/build/Debug/serialport.node
 → /home/chenhao/Desktop/comDemo/node_modules/serialport/build/Release/serialport.node
 → /home/chenhao/Desktop/comDemo/node_modules/serialport/out/Debug/serialport.node
 → /home/chenhao/Desktop/comDemo/node_modules/serialport/Debug/serialport.node
 → /home/chenhao/Desktop/comDemo/node_modules/serialport/out/Release/serialport.node
 → /home/chenhao/Desktop/comDemo/node_modules/serialport/Release/serialport.node
 → /home/chenhao/Desktop/comDemo/node_modules/serialport/build/default/serialport.node
 → /home/chenhao/Desktop/comDemo/node_modules/serialport/compiled/0.10.25/linux/x64/serialport.node
    at bindings (/home/chenhao/Desktop/comDemo/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/chenhao/Desktop/comDemo/node_modules/serialport/lib/bindings.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/chenhao/Desktop/comDemo/node_modules/serialport/lib/serialport.js:16:25)
    at Module._compile (module.js:456:26)

**Comment by buzai** [comment]
已经解决，需要安装vs，python，node-pre-gpy，安装的模块的时候会提示rebuild，会花一段时间等着就好了，编译好了就可以使用了

**Comment by xianyanbu** [comment]
```
嗯，那就好。
```

1046778499@qq.com

发件人： chenLX
发送时间： 2016-05-22 22:36
收件人： xianyanbu/serialport
抄送： xianyanbu; Comment
主题： Re: [xianyanbu/serialport] serialport这个模块在win上貌似不工作，打开你的bat后无法访问 (#1)
已经解决，需要安装vs，python，node-pre-gpy，安装的模块的时候会提示rebuild，会花一段时间等着就好了，编译好了就可以使用了
